/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('fs');

/**
 * Simple .env file parser to avoid external dependencies in setup-env.js
 */
function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const result = {};
    content.split(/\r?\n/).forEach(line => {
      const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
      if (match) {
        let value = match[2] ? match[2].trim() : '';
        if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
        if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1);
        result[match[1]] = value;
      }
    });
    return result;
  } catch (err) {
    return {};
  }
}

// Sprawdź aktualną gałąź
let currentBranch = 'main';
try {
  const { execSync } = require('child_process');
  currentBranch = execSync('git branch --show-current', { encoding: 'utf8' }).trim() || 'main';
} catch (error) {
  currentBranch = process.env.GIT_BRANCH || 'main';
}

console.log(`Current branch: ${currentBranch}`);

// Załaduj istniejące zmienne z plików .env, aby skrypt je widział
const dotEnv = parseEnvFile('.env');
const dotEnvLocal = parseEnvFile('.env.local');
const combinedEnv = { ...process.env, ...dotEnv, ...dotEnvLocal };

const isLocal = !process.env.CI && !process.env.VERCEL;

// Lokalnie preferujemy DATABASE_URL_DEV, na produkcji DATABASE_URL zależnie od gałęzi
const databaseUrl = isLocal
  ? (combinedEnv.DATABASE_URL_DEV || combinedEnv.DATABASE_URL)
  : (currentBranch === 'dev' ? combinedEnv.DATABASE_URL_DEV : combinedEnv.DATABASE_URL);

const nextAuthSecret = combinedEnv.NEXTAUTH_SECRET;
const nextAuthUrl = combinedEnv.NEXTAUTH_URL || 'http://localhost:3000';
const jwtSecret = combinedEnv.JWT_SECRET;
const finnhubApiKey = combinedEnv.FINNHUB_API_KEY;
const cryptocompareApiKey = combinedEnv.CRYPTOCOMPARE_API_KEY;

// Lokalnie zawsze development, na serwerze zależnie od gałęzi
const nodeEnv = isLocal ? 'development' : (currentBranch === 'dev' ? 'development' : 'production');

// Walidacja wymaganych zmiennych
const missingVars = [];
if (!databaseUrl) missingVars.push(isLocal ? 'DATABASE_URL_DEV' : (currentBranch === 'dev' ? 'DATABASE_URL_DEV' : 'DATABASE_URL'));
if (!nextAuthSecret) missingVars.push('NEXTAUTH_SECRET');
if (!jwtSecret) missingVars.push('JWT_SECRET');

if (missingVars.length > 0) {
  console.warn('⚠️  Warning: Missing environment variables:');
  missingVars.forEach(varName => console.warn(`   - ${varName}`));
  if (process.env.CI) process.exit(1);
}

// Stwórz treść .env.local
const envContent = `# Auto-generated by setup-env.js for ${currentBranch} branch

DATABASE_URL="${databaseUrl || ''}"
DATABASE_URL_DEV="${combinedEnv.DATABASE_URL_DEV || ''}"
NEXTAUTH_SECRET="${nextAuthSecret || ''}"
NEXTAUTH_URL="${nextAuthUrl}"
JWT_SECRET="${jwtSecret || ''}"
NODE_ENV="${nodeEnv}"
FINNHUB_API_KEY="${finnhubApiKey || ''}"
CRYPTOCOMPARE_API_KEY="${cryptocompareApiKey || ''}"
`;

// Nadpisz .env.local tylko jeśli zaszła zmiana lub plik nie istnieje
// Dzięki temu nie psujemy cache'u Next.js jeśli nie trzeba
if (!fs.existsSync('.env.local') || fs.readFileSync('.env.local', 'utf8') !== envContent) {
  fs.writeFileSync('.env.local', envContent);
  console.log(`✅ .env.local has been updated for ${isLocal ? 'local' : currentBranch} development`);
} else {
  console.log(`✅ .env.local is already up to date`);
}

console.log(`🌍 Environment: ${nodeEnv}`);
if (databaseUrl) {
  const obscuredUrl = databaseUrl.replace(/:([^@]+)@/, ':****@').substring(0, 60);
  console.log(`📊 Database: ${obscuredUrl}...`);
}
